services:
  music-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - ./music:/music:ro  # Read-only mount of music files
    environment:
      - RUST_LOG=info
      - PORT=3500
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3500/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - music-net

networks:
  music-net:
    driver: bridge